[features]
resolution = true
skip-lint = false

[programs.localnet]
market_engine = "6Shg7A31xbWRz9uQ8Y8nYUBXqQ2w4z5nP6Rjz7gkKMEn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"
